BtkAkademiKurs/Models/Candidate.cs
using System.ComponentModel.DataAnnotations;

namespace BtkAkademiKurs.Models
{
    public class Candidate
    {
        [Required(ErrorMessage ="Email is required.")]
        public string? Email { get; set; } = String.Empty;
        [Required(ErrorMessage = "FirstName is required.")]
        public string? FirstName { get; set; } = String.Empty;
        [Required(ErrorMessage = "LastName is required.")]
        public string? LastName { get; set; } = String.Empty;
        public string? FullName => $"{FirstName} {LastName?.ToUpper()}";
        [Required(ErrorMessage = "Age is required.")]
        public int? Age { get; set; }
        public string? SelectedCourse { get; set; } = String.Empty;
        public DateTime ApplyAt { get; set; }
        public Candidate()
        {
            ApplyAt = DateTime.Now;
        }
    }
}

BtkAkademiKurs/Models/ErrorViewModel.cs
namespace BtkAkademiKurs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BtkAkademiKurs/Models/Repository.cs
namespace BtkAkademiKurs.Models
{
    public static class Repository
    {
        private static List<Candidate> applications = new();
        public static IEnumerable<Candidate> Applications => applications;
        public static void Add(Candidate candidate)
        {
            applications.Add(candidate);
        }
    }
}

BtkAkademiKurs/Controllers/CourseController.cs
using BtkAkademiKurs.Models;
using Microsoft.AspNetCore.Mvc;

namespace BtkAkademiKurs.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            var model = Repository.Applications;
            return View(model);
        }
        public IActionResult Apply()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Apply([FromForm] Candidate model)
        {
            if (Repository.Applications.Any(c => c.Email.Equals(model.Email)))
            {
                ModelState.AddModelError("", "There is already an application for you");
            }
            if (ModelState.IsValid)
            {
                Repository.Add(model);
                return View("Feedback", model);
            }
            return View();
        }
    }
}

BtkAkademiKurs/Controllers/HomeController.cs
using BtkAkademiKurs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BtkAkademiKurs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BtkAkademiKurs/Views/Course/Apply.cshtml
@model Candidate
<div class="display-6">
    Apply
</div>
<form method="post" asp-controller="course" asp-action="apply">
    <div class="form-group my-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group my-2">
        <label asp-for="FirstName">FirstName</label>
        <input asp-for="FirstName" class="form-control" />
    </div>
    <div class="form-group my-2">
        <label asp-for="LastName">LastName</label>
        <input asp-for="LastName" class="form-control" />
    </div>
    <div class="form-group my-2">
        <label asp-for="Age">Age</label>
        <select asp-for="Age" class="form-control">
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20" selected>20</option>
            <option value="21">21</option>
            <option value="22">22</option>
        </select>
    </div>
    <div class="form-group my-2">
        <fieldset>
            <legend>Select One Course</legend>
            <p>
                <input value="ASP.NET Core MVC" type="radio" asp-for="SelectedCourse" checked />
                <label>ASP.NET Core MVC</label>
            </p>
            <p>
                <input value="ASP.NET Core API" type="radio" asp-for="SelectedCourse" />
                <label>ASP.NET Core API</label>
            </p>
            <p>
                <input value="Blazor" type="radio" asp-for="SelectedCourse" />
                <label>Blazor</label>
            </p>
        </fieldset>
    </div>

    <div class="form-group my-2">
        <button class="btn btn-primary">Apply</button>
        <a class="btn btn-warning" asp-controller="home">Home</a>
    </div>

</form>

BtkAkademiKurs/Views/Course/Feedback.cshtml
@model Candidate

<div>
    <h3 class="display-4">Congratulations</h3>
    <p class="lead">Your applications has been <mark>accepted</mark>.</p>
    <p class="lead">Many thanks for your interest</p>
    <hr />
    <blockquote>
        You have enrolled to @Model.SelectedCourse course.
    </blockquote>
    <p class="text-muted">You applied at @Model.ApplyAt</p>
    <a class="btn btn-outline-success" href="#">Applications</a>
    <a class="btn btn-success" asp-controller="home" asp-action="index">Home</a>
</div>

BtkAkademiKurs/Views/Course/Index.cshtml
@model IEnumerable<Candidate>

@if (Model.Count() > 0)
{
    <h6>Applications(@Model.Count())</h6>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Email</th>
                <th>FullName</th>
                <th>Apply At</th>
                <th>Course</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Candidate candidate in Model)
            {
                <tr>
                    <td>@candidate.Email</td>
                    <td>@candidate.FullName</td>
                    <td>@candidate.ApplyAt</td>
                    <td>@candidate.SelectedCourse</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">
        There is no application.Please click here to
        <a asp-controller="course" asp-action="Apply">Apply</a>.
    </div>
}

BtkAkademiKurs/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hoş Geldiniz</h1>
    <p>
        <a class="btn btn-primary" asp-controller="course" asp-action="apply">Apply</a>
    </p>
</div>

BtkAkademiKurs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BtkAkademiKurs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BtkAkademiKurs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BtkAkademiKurs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Apply">Apply</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Applications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BtkAkademiKurs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>